default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails-practice-add-rspec_development
test:
  <<: *default
  database: rails-practice-add-rspec_test
